routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Locker;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

//

//Route::get('/logerror', function(){
//    Log::listen(function($level, $message, $context)
//    {
//        dd($message); // fail
//    });
////   dd( Log::error('fail'));
//});
Route::group(['middleware' => ['auth']], function () {

    Route::get('script/fixCode/{id}', 'Backend\AdminController@fixCodes')->name('fixCodes');

    Route::get('/user/checkCredits', 'Frontend\LockersController@checkSms');

    Route::post('admin/changeSalePrice', 'Backend\paymentController@changeSalePrice')->name('changeSalePrice');

    Route::get('user/getSaveAddress', 'Frontend\AddressController@getUserAddress')->name('getSaveAddress');
    Route::post('user/saveUserAddress', 'Frontend\AddressController@saveUserAddress')->name('saveUserAddress');

    Route::resource('admin/emailtemplates', 'Backend\EmailTemplateController')->middleware('EmailTemplateManagement');
    Route::post('admin/getemailtemplate', 'Backend\EmailTemplateController@getemailtemplate')->name('getemailtemplate');
    Route::post('admin/updateemailtemplate', 'Backend\EmailTemplateController@updateemailtemplate')->name('updateemailtemplate');

    Route::get('/admin', 'Backend\AdminController@index');

    Route::resource('admin/pages', 'Backend\PageController');


    //users
    Route::group(['prefix' => 'admin/users', 'as' => 'users.' ,'middleware' => ['UserManagment']], function () {
        Route::get('', 'Backend\UserController@index')->name('index');
        Route::post('store', 'Backend\UserController@store')->name('store');
        Route::put('update/{id}', 'Backend\UserController@update')->name('update');
        Route::delete('destroy/{id}', 'Backend\UserController@destroy')->name('destroy');
        Route::get('show/all', 'Backend\UserController@show_all')->name('show.all');

    });
     Route::post('admin/userCompanyFranchise', 'Backend\UserController@companyFranchise')->name('user.compnay.companyFranchise');
    Route::post('admin/getuserroles', 'Backend\UserController@getuserroles')->name('getuserroles');
    Route::post('admin/companygetuserroles', 'Backend\Company\CompanyUserController@getuserroles')->name('compnay.getuserroles');

     Route::post('admin/companyFranchise', 'Backend\Company\CompanyUserController@companyFranchise')->name('compnay.companyFranchise');

    Route::get('admin/editprofile', 'Backend\UserController@editprofile');
    Route::post('admin/saveprofile', 'Backend\UserController@saveprofile')->name('saveprofile');

    //roles
    Route::resource('admin/roles', 'Backend\RoleController')->middleware('RollManagement');
    Route::post('admin/getroles', 'Backend\RoleController@getroles')->name('getroles');

    // BlockGroup
    Route::group(['prefix' => 'admin/block-group', 'as' => 'blockgroup.','middleware' => ['BlockGroup']], function () {
         Route::get('', 'Backend\BlockgroupController@index')->name('index');
         Route::post('', 'Backend\BlockgroupController@store')->name('store');
       Route::post('show/all', 'Backend\BlockgroupController@show_all')->name('show.all');
       Route::post('update/sort', 'Backend\BlockgroupController@updateOrder')->name('update.order');
       Route::post('update/status', 'Backend\BlockgroupController@updateStatus')->name('update.status');
       Route::post('update/name', 'Backend\BlockgroupController@updateName')->name('update.name');
       Route::post('update/delete', 'Backend\BlockgroupController@deleteBlock')->name('update.deleteBlock');




    });
   
    // locker Description
    Route::group(['prefix' => 'admin/locker-description', 'as' => 'locker_description.','middleware' => ['LockerDescription'] ], function () {
         Route::get('', 'Backend\LockerDescription@index')->name('index');
         Route::post('', 'Backend\LockerDescription@store')->name('store');
       Route::post('show/all', 'Backend\LockerDescription@show_all')->name('show.all');
       // Route::post('update/sort', 'Backend\LockerDescription@updateOrder')->name('update.order');
       Route::post('update/status', 'Backend\LockerDescription@updateStatus')->name('update.status');
       Route::post('update/delete', 'Backend\LockerDescription@deleteBlock')->name('update.deleteBlock');
       Route::post('update/active', 'Backend\LockerDescription@updateActive')->name('update.active');




    });

    //Companies
    Route::group(['prefix' => 'admin/company', 'as' => 'company.','middleware' => ['BlockLinkforUser']], function () {
        Route::get('', 'Backend\CompanyController@index')->name('index');
        Route::get('create', 'Backend\CompanyController@create')->name('create');
        Route::post('store', 'Backend\CompanyController@store')->name('store');
        Route::put('update/{id}', 'Backend\CompanyController@update')->name('update');
        Route::delete('destroy/{id}', 'Backend\CompanyController@destroy')->name('destroy');
        Route::get('show/all', 'Backend\CompanyController@show_all')->name('show.all');
        Route::get('show/deleted', 'Backend\CompanyController@show_deleted')->name('show.deleted');
        Route::get('show/{id}', 'Backend\CompanyController@show')->name('show');
        Route::get('info', 'Backend\CompanyController@info')->name('info');

    });


    // Current Locker Offsale
    Route::group(['prefix' => 'admin/reports/currentlocker', 'as' => 'company.currentlocker.','middleware' => ['MaintanceOffsaleReport']], function () {
        Route::get('index', 'Backend\CurrentMaintenaceController@index');
        Route::get('current_show', 'Backend\CurrentMaintenaceController@currentlocker_show');
        Route::post('/count', 'Backend\CurrentMaintenaceController@offsaleCount')->name('offsaleCount');
        Route::post('get/data', 'Backend\CurrentMaintenaceController@getData')->name('getData');
    });

    //Company Document routes
    Route::group(['prefix' => 'admin/company/documents', 'as' => 'company.documents.'], function () {
        Route::get('', 'Backend\CompanyDocumentController@index')->name('index');
        Route::get('show/all', 'Backend\CompanyDocumentController@show_all')->name('show.all');
        Route::get('download/{id}', 'Backend\CompanyDocumentController@download')->name('download');
        Route::post('upload', 'Backend\CompanyDocumentController@upload')->name('storefile');
        Route::post('update', 'Backend\CompanyDocumentController@update')->name('update');
        Route::post('show', 'Backend\CompanyDocumentController@show')->name('show');
        Route::get('destroy/{id}', 'Backend\CompanyDocumentController@destroy')->name('delete');
    });
    //Document routes
    Route::group(['prefix' => 'admin/documents', 'as' => 'documents.','middleware' => ['DocumentManagment']], function () {
        Route::get('', 'Backend\DocumentController@index')->name('index');
        Route::get('show/all', 'Backend\DocumentController@show_all')->name('show.all');
        Route::get('download/{id}', 'Backend\DocumentController@download')->name('download');
        Route::post('upload', 'Backend\DocumentController@upload')->name('store');
        Route::post('update', 'Backend\DocumentController@update')->name('update');
        Route::post('show', 'Backend\DocumentController@show')->name('show');


    });
    // Company Outer Blocks Routs
    Route::group(['prefix' => 'admin/company/outer/blocks', 'as' => 'company.outer.blocks.'], function () {
        Route::get('', 'Backend\OuterBlockController@index')->name('index');
        Route::get('create', 'Backend\OuterBlockController@create')->name('create');
        Route::delete('destroy/{id}', 'Backend\OuterBlockController@destroy')->name('destroy');
        Route::get('show/all', 'Backend\OuterBlockController@show_all')->name('show.all');
        Route::get('show/delete', 'Backend\OuterBlockController@show_deleted')->name('show.delete');
        Route::get('show/{id}', 'Backend\OuterBlockController@show')->name('show');
    });


    // Company Outer Locker Blocks
    Route::group(['prefix' => 'admin/company/locker/blocks/images', 'as' => 'company.locker.blocks.images.' ,'middleware' => ['LockerBlockImages']], function () {
        Route::get('', 'Backend\Company\LockerBlockImagesController@index')->name('index');
        Route::get('show/all', 'Backend\Company\LockerBlockImagesController@show_all')->name('show.all');
        Route::post('upload', 'Backend\Company\LockerBlockImagesController@upload')->name('upload');
        Route::post('/update', 'Backend\Company\LockerBlockImagesController@update')->name('update');
        Route::post('/editabledata', 'Backend\Company\LockerBlockImagesController@editabledata')->name('editabledata');

    });

    //company blocks in Company
    Route::get('blocks/getUpdated', 'Backend\CompanyBlockController@getUpdated');
    Route::any('blocks/update/{id}', 'Backend\CompanyBlockController@update');
    Route::any('blocksouter/update/{id}', 'Backend\OuterBlockController@update');
    Route::post('blocks/store', 'Backend\CompanyBlockController@store')->name('store');
    Route::post('blocks/tiers', 'Backend\CompanyBlockController@findTier');

     Route::post('status/go_live', 'Backend\CompanyController@addLiveStatus');

    Route::get('getSchoolYear', 'Backend\CompanyBlockController@getSchoolYear')->name('getSchoolYear');
    Route::get('updatetheSchoolyearCheck', 'Backend\CompanyBlockController@updateSchoolYears')->name('updatetheSchoolyearCheck');


    Route::get('getBlockImages', 'Backend\CompanyBlockController@getBlockImages')->name('getBlockImages');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Company extends Model
{

    protected $fillable = [
        'location_group_id', 'currency', 'name', 'stop_auto_rebook', 'name_number', 'street', 'city',  'country', 'post_code', 'active', 'display'.'keep_block', 'general_email','telephone'
    ];

    public function Chats()
    {
        return $this->hasMany('App\Chat','company_id');
    }

    public function franchisee_companies()
    {
        return $this->hasOne('App\FranchiseeCompany','company_id');

    }
    public function locationGroup()
    {
        return $this->belongsTo('App\LocationGroup','location_group_id');
    }
    public function blocks()
    {
        return $this->hasMany('App\Block','company_id')->orderBy('company_id');

    }
    public function company_errors()
    {
        return $this->hasMany('App\CompanyBlockError','company_id');

    }
    public function sales()
    {
        return $this->hasMany('App\Sale','company_id','id');

    }
    public function lockers()
    {
        return $this->hasMany('App\Locker','company_id','id');

    }
    public function maintenances()
    {
        return $this->hasMany('App\Maintenance','company_id','id');

    }
    public function academicYearReports()
    {
        return $this->hasMany('App\AcademicYearReport','company_id');

    }
    public function voucherCodes()
    {
        return $this->hasMany('App\VoucherCode','company_id');

    }
    public function franchise()
    {
        return $this->belongsTo('App\Franchisee','territory_code');
    }

    //record permission on the basis of admin, franchise group & direct company assigned & user
    public function company_record_permissions($company)
    {
        $user = Auth::user();
        $franchisees = $user->franchisee()->pluck('franchisee_id')->toArray();

        if(auth()->user()->can('All Records')) {

        }elseif( Auth::user()->company_id && $franchisees) {
            $franchisee_companies = FranchiseeCompany::whereIn('franchisee_id',$franchisees)->pluck('company_id')->toArray();
            if (!empty($franchisee_companies)) {
                array_push($franchisee_companies, auth()->user()->company_id);
                $company->Where(function ($query) use ($franchisee_companies) {
                    $query->WhereIn('id', $franchisee_companies);
                        // ->orWhere('id', Auth::user()->company_id);
                });
            }else{
                $company->Where(function ($query)  {
                    $query->Where('id', Auth::user()->company_id);
                });
            }
        }
        elseif($franchisees ) {

            $franchisee_companies = FranchiseeCompany::whereIn('franchisee_id',$franchisees)->pluck('company_id')->toArray();

            $company->whereIn('id',$franchisee_companies);
        }
        elseif( Auth::user()->company_id ){

            $company->where('id',Auth::user()->company_id);
        }else{
            $company->where('id',0);
        }
        return $company;
    }
}

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    protected $table = 'documents';
    
    protected $fillable = [
        'title', 'type_id', 'original_path', 'converted_path', 'uploaded_by', 'company_id'
    ];
    public function user()
    {
        return $this->belongsTo('App\User','uploaded_by');
    }
    public function company()
    {
        return $this->belongsTo('App\Company','company_id');
    }
    public function document_type()
    {
        return $this->belongsTo('App\DocumentTypes','type_id');
    }
}

app/DocumentTypes.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;

class DocumentTypes extends Model
{
    protected $table = 'document_types';

}

app/Http/Controllers/Backend/Company/LockerBlockImagesController.php
<?php

namespace App\Http\Controllers\Backend\Company;

use App\FranchiseeCompany;
use Carbon\Carbon;
use App\LockerBlockImage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;
use App\User;
use App\Document;
use App\Session;
use App\OfficeConverter;

class LockerBlockImagesController extends Controller
{
    public function index()
    {
        return view('backend.pages.company.lockerBlockImage.index');
    }

    public function show_all(Request $request)
    {
        $data = $this->query_data($request);
        return Datatables::of($data)
        //   ->editColumn('file_name', function($data) {
      
        //     return '<a target="_blank" href="/uploads/'.$data->file_name.'" class="image-click"> <img class="block-images" src="/uploads/'.$data->file_name.'"></a>';
        // })
            ->addColumn('image_type', function ($data) {
                if($data->image_type == 'I')
                    return 'Internal';
                else
                    return 'External';
            })
            ->addColumn('action', function ($data) {
                $buttons = '';
                $buttons = '<a href="javascript:void(0)" class="btn btn-primary btn-md adv_cust_mod_btn pull-left edit-document" id="open_block_modal"  data-id="' . $data->id . '"  data-tier="'.$data->tier.'" data-imageType="'.$data->image_type.'" data-image="'.$data->file_name.'" style="margin-right: 3px;">Edit</a>';
                return $buttons;
            })
           
            ->rawColumns(['file_name', 'action']) ->make(true);
    }

    public function query_data($request)
    {
        $query = LockerBlockImage::orderBy('tier')->get();
        return $query;
    }

    public function upload(Request $request)
    {
        // dd($request->all());
        $validatedData = $request->validate([
            'file_name' => ['required'],
            'image_type' => ['required'],
            'tier' => ['required']
        ]);

        if (isset($request->file_name)) {
            // $time = time();
            $file = $request->file('file_name');
            $name = $file->getClientOriginalName();
            // dd($name);
            $file_name = explode(".", $name);
            $attachments = $file_name[0] . '.' . $file->getClientOriginalExtension();
            $destinationPath = public_path('uploads');

        }
        LockerBlockImage::create([
            'file_name' => $attachments,
            'image_type' => $request->image_type,
            'tier' => $request->tier,
            'active' => '1',
            'deleted' => '0',
        ]);
        return response()->json($validatedData);
    }

    public function update(Request $request)
    {
        $LockerBlockImage = LockerBlockImage::find($request->id);
        $validatedData = $request->validate([
            'image_type' => ['required'],
            'tier' => ['required']
        ]);
        if (isset($request->file_name)) {
            $file = $request->file('file_name');
            $name = $file->getClientOriginalName();
            // dd($name);
            $file_name = explode(".", $name);
            $attachments = $file_name[0] . '.' . $file->getClientOriginalExtension();
            $destinationPath = public_path('uploads');
            //dd($attachments);
            $file->move($destinationPath, $attachments);
            $LockerBlockImage->file_name = $attachments;
        }

        $LockerBlockImage->image_type = $request->image_type;
        $LockerBlockImage->tier = $request->tier;
        $LockerBlockImage->save();

        return response()->json($validatedData);
    }

    public function editabledata(Request $request)
    {
        $LockerBlockImage = LockerBlockImage::find($request->id);
        return response()->json($LockerBlockImage);
    }
}

resources/views/backend/pages/company/documents/create.blade.php
<div class="modal fade in display_none" id="create_document" style="overflow-y: scroll;" tabindex="-1" role="dialog"
    aria-hidden="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-md-12">
                                <h3><i class="fa fa-pencil circle"></i> Create Document</h3>
                            </div>
                        </div>
                        <hr>
                        <div class="loader" id="block_loader">
                        </div>
                        <form id="documentsForm" enctype="multipart/form-data">
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <label name="title">Title</label>
                                    <input type="text" name="title" id="title"
                                        class="input_empty document-title-border form-control">
                                </div>
                                <div id="document_title_error" class="col-md-12 document_error "></div>
                                <div class='form-group col-md-12'>
                                    <label for="document_type">Type</label>
                                    <select class="form-control input_empty" name="document_type"
                                        id="choose_document_type">
                                        <option value="">Choose Document Type</option>
                                        @foreach($document_types->where('location', 'Company')->where('active', '1') as
                                        $document_type)
                                        <option value="{{$document_type->id}}">{{$document_type->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div id="document_type_error" class="col-md-12 document_error"></div>

                                <div class="form-group col-md-12">
                                    <br>
                                    <label for="file" class="upload-area" id="uploadfile">
                                        <i class="fas fa-cloud-upload-alt"></i>
                                        <h1 id="drag_text">Click or drop file here</h1>
                                    </label>
                                    <br>
                                    <input id="file" name="file" type="file" style="display:none" />
                                </div>
                                <div id="document_file_error" class="col-md-12 document_error"></div>
                            </div>
                            <div class="modal-footer" style="display: flex;">
                                <button type="button" data-dismiss="modal" class="btn cancel btn-light">Cancel</button>
                                <button type="submit" class="btn btn-primary" id="create_document_btn">Upload</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script type="text/javascript" src="/backend/vendors/switchery/js/switchery.min.js"></script>
<script type="text/javascript" src="/backend/js/jquery.min.js"></script>

<script type="text/javascript">
    $( document ).ready(function() {
        $(function () {
        // preventing page from redirecting
        $("html").on("dragover", function (e) {
            e.preventDefault();
            e.stopPropagation();
            $("h1").text("Drag Your File Here!");
        });

        $("html").on("drop", function (e) {
            e.preventDefault();
            e.stopPropagation();
            file = e.originalEvent.dataTransfer.files;
            console.log()
            $("#drag_text").text(file[0].name);
            dragcheck = 2;
        });

        // Drag enter
        $('.upload-area').on('dragenter', function (e) {
            e.stopPropagation();
            e.preventDefault();
            $("h1").text("Drop Here!");
        });

        // Drag over
        $('.upload-area').on('dragover', function (e) {
            e.stopPropagation();
            e.preventDefault();
            $("h1").text("Drop Here!");
        });
        // file selected
        $("#file").change(function () {
            var filees = $("#file").val();
            var filename = filees.split('\\').pop();
            $("#drag_text").text(filename);
            dragcheck=0;
        });
        });
        $("#documentsForm").submit(function(event){
            spinner_start();
            event.preventDefault();
            $('button#create_document_btn').prop('disabled', true);
            formdata =  new FormData(this);
            if(dragcheck == 2){
                formdata.append('file', file[0]);
                console.log(file[0]);
                dragcheck = 0;
            }
           
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                type: "POST",
                url: '{{route('company.documents.storefile')}}',
                data: formdata,
                // dataType:'JSON',
                contentType:false,
                cache:false,
                processData:false,
                
                success: function(){
                    spinner_close();
                    $("#documentsForm")[0].reset();
                    $("h1").text("Click or drop file here");
                    $('#create_document').modal('hide');
                    $('#edit').modal('show');
                    $('button#create_document_btn').prop('disabled', false);
				    documentsTable();
                },
                error: function (xhr) {
                    spinner_close();
                    $('.document_error').show();
                    $('button#create_document_btn').prop('disabled', false);

                    if(xhr.responseJSON.errors.title){
                        $('#document_title_error').show();
                        $('#document_title_error').html('<span>'+ xhr.responseJSON.errors.title[0] + '</span>');
                    }
                    else{
                        $('#document_title_error').hide();
                    }

                    if(xhr.responseJSON.errors.document_type){
                        $('#document_type_error').show();  
                        $('#document_type_error').html('<span>'+ xhr.responseJSON.errors.document_type[0] + '</span>');
                    }
                    else{
                        $('#document_type_error').hide();
                    }
                  
                    if(xhr.responseJSON.errors.file){
                        $('#document_file_error').show();
                        $('#document_file_error').html('<span>'+ xhr.responseJSON.errors.file[0] + '</span>');
                    }
                    else{
                        $('#document_file_error').hide();
                    }
                }
            });
        });

    });

</script>

resources/views/backend/pages/company/documents/index.blade.php
<div class="card-body">
    <div class="row">
        <div class="col-md-12">
            <a href="#create_document" class="input_create_document_empty btn btn-primary" data-toggle="modal"
                style="float: right; margin-top: 12px; margin-right: 62px; ">Add</a>

        </div>
    </div>
    <br>
    <div class="row" style="width: 100% !important;">
        <div class="col-md-12">
            <table class="table  table-bordered table-hover" id="documentsTable" style="width: 100% !important;">
                <thead>
                    <tr>
                        <th style="width:220px">Title</th>
                        <th style="width:220px">Type</th>
                        <!-- <th style="width:220px">Uploaded By</th>
                        <th style="width:220px">Date Updated</th> -->
                        <th style="width:220px">Details</th>
                        <th style="width:330px">&nbsp;</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>



<script type="text/javascript">
  
    function documentsTable() {
        $('#documentsTable').dataTable().fnClearTable();
        $('#documentsTable').dataTable().fnDestroy();

        return $('#documentsTable').DataTable({
            initComplete : function() {
                $("#documentsTable_wrapper>.row").attr('style','width:100%;');
                $("#documentsTable_filter>label").css('float', 'right');
                $("#documentsTable_length>label").css('float', 'left');
            },
            "order":[[0,'desc'],[1,'asc']],
            "order": [],
            language: {
                'lengthMenu': '_MENU_',
                "search": '',
                "searchPlaceholder": "Search..."
            },


            "autoWidth": false,

            "columnDefs": [
                { "width": "220px", "targets": 0 },
                { "width": "220px", "targets": 1 },
                { "width": "220px", "targets": 2 },
                { "width": "330px", "targets": 3 },
                // { "width": "220px", "targets": 4 },
            ],
            ajax: '<?php echo route('company.documents.show.all'); ?>',
            columns: [
                {data: 'title', name: 'title'},
                {data: 'type_id', name: 'type_id'},
                {data: 'details', name: 'details'},
                // {data: 'updated_at', name: 'updated_at'},
                {data: 'action', name: 'action', orderable: false, searchable: true}
            ],

        });

    }
</script>